spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./carrental-db;AUTO_SERVER=TRUE' #mixed mode
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

users:
  admin:
    username: 'admin'
    name: 'Admin Nadminny'
    email: 'admin@company.com'
    role: 'ADMIN'
    password: 'admin'
dev-settings:
  max-fake-users: 25


